# This is a basic workflow to help you get started with Actions

name: Connect to an AWS role from a GitHub repository

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AWS_REGION : "eu-west-2" #Change to reflect your Region
  
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git clone the repository
        uses: actions/checkout@v4
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::684361860346:role/GitHub-OIDC-role #<arn:aws:iam::111122223333:role/GitHubAction-AssumeRoleWithAction> #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
     
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      # Runs a single command using the runners shell
      - name: Terraform format
        run: terraform fmt -recursive


      # Runs a set of commands using the runners shell
      - name: Teraform Init and Validate
        run: |
          terraform init
          terraform validate

      # Runs a single command using the runners shell
      - name: Terraform Plan
        run: terraform plan -out plan.out
